### ISSUE TITLE
kext does not work

### ISSUE THREAD

**Issue by graphis** [kfatehi/blog#1]
I can compile this simple kext, but there are problems with it. El Sierra dows not run this kext.

.. The Mach-O filetype 0x1 is not supported on the target architecture.
(kernel) Can't load kext com.test.ikext - link failed.
(kernel) Failed to load executable for kext com.test.kext
(kernel) Kext com.test.ikext failed to load (0xdc008016).
(kernel) Failed to load kext com.test.ikext (error 0xdc008016).
Failed to load ./ikext.ikext - (libkern/kext) link error.
Failed to load ./ikext.ikext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).

what to do to compile kext under  El Sierra?

**Comment by kfatehi** [comment]
I was curious about what El Sierra is so I checked the wikipedia for the last few releases and their names:

4.11	OS X 10.9 Mavericks
4.12	OS X 10.10 Yosemite
4.13	OS X 10.11 El Capitan
4.14	macOS 10.12 Sierra
4.15	macOS 10.13 High Sierra

Unfortunately I can't advise about the kext stuff -- I've only ever had to mess with that stuff once back when I used to do hackintosh. good luck
